################################# Default configuration ###################
# provide your domain here
baseURL = "https://www.dataskills.training/"
# theme
theme = "dot"
# site title
title = ""
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "about"
url = "about"
weight = 1

[[menu.main]]
name = "Personas"
url = "personas"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "topics"
hasChildren = true

  [[menu.main]]
  parent = "topics"
  name = "Starting with data"
  url = "topic-1"
  weight = 1

  [[menu.main]]
  parent = "topics"
  name = "Data management"
  url = "topic-2"
  weight = 2
  
  [[menu.main]]
  parent = "topics"
  name = "Discovering & reusing data"
  url = "topic-3"
  weight = 3
  
  [[menu.main]]
  parent = "topics"
  name = "Cleaning data"
  url = "topic-4"
  weight = 4

  [[menu.main]]
  parent = "topics"
  name = "Data analysis"
  url = "topic-5"
  weight = 5
  
  [[menu.main]]
  parent = "topics"
  name = "Data visualisation"
  url = "topic-6"
  weight = 6
  
  [[menu.main]]
  parent = "topics"
  name = "Reusable data & sharing"
  url = "topic-7"
  weight = 7
  
  [[menu.main]]
  parent = "topics"
  name = "Data tools"
  url = "topic-8"
  weight = 8


  [[menu.main]]
  parent = "topics"
  name = "Publishers & funder policies"
  url = "topic-9"
  weight = 9
  
[[menu.main]]
name = "Blog"
url = "post"
weight = 4

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "images/dataskills-colour.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = "images/dataskills-white-gray.png"
# when logo is empty, it will shown your site title

# customize color
primary_color = "#78463F"
secondary_color = "#8D473F"
body_color = "#F7F5F3"
text_color = "#2E2923"
text_color_dark = "#26221D"
white_color = "#ffffff"
light_color = "#F7F5F3"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/aneldavdw"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/anelda/data-skills-101"
  

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-uk"
weight = 1
home = "Home"
copyright = "[DATASKILLS]( https://www.dataskills.training/about/) is created with love in Africa under a [CC-BY-NC-4.0](https://creativecommons.org/licenses/by-nc/4.0/) license"
conduct = "Code of Conduct"
contribute = "Contribute"

# banner
[Languages.en.params.banner]
title = "Data Skills for the 21st Century"
subtitle = "Start from where you are"
bg_image = "images/banner.jpg"
placeholder = "Looking for a resource? Enter keywords to see if we can help you or get in touch"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question? Want to contribute resources?"
content = "This site is under constant development and we'd love to grow it to be as comprehensive and helpful as possible."
# call to action button

[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"

